/** Adapted from https://github.com/stashapp/stash/blob/0621d87133a9e810687e0da27fd3ea65095873a0/ui/v2.5/src/pluginApi.d.ts */
declare namespace PluginApi {
  const React: typeof import("react");
  const ReactDOM: typeof import("react-dom");
  namespace GQL {
    const AddGalleryImagesDocument: { [key: string]: unknown };
    const AddTempDlnaipDocument: { [key: string]: unknown };
    const AnonymiseDatabaseDocument: { [key: string]: unknown };
    const AvailablePluginPackagesDocument: { [key: string]: unknown };
    const AvailableScraperPackagesDocument: { [key: string]: unknown };
    const BackupDatabaseDocument: { [key: string]: unknown };
    const BlobsStorageType: { [key: string]: unknown };
    const BulkGalleryUpdateDocument: { [key: string]: unknown };
    const BulkImageUpdateDocument: { [key: string]: unknown };
    const BulkGroupUpdateDocument: { [key: string]: unknown };
    const BulkPerformerUpdateDocument: { [key: string]: unknown };
    const BulkSceneUpdateDocument: { [key: string]: unknown };
    const BulkUpdateIdMode: { [key: string]: unknown };
    const CircumisedEnum: { [key: string]: unknown };
    const ConfigDataFragmentDoc: { [key: string]: unknown };
    const ConfigDefaultSettingsDataFragmentDoc: { [key: string]: unknown };
    const ConfigDlnaDataFragmentDoc: { [key: string]: unknown };
    const ConfigGeneralDataFragmentDoc: { [key: string]: unknown };
    const ConfigInterfaceDataFragmentDoc: { [key: string]: unknown };
    const ConfigScrapingDataFragmentDoc: { [key: string]: unknown };
    const ConfigurationDocument: { [key: string]: unknown };
    const ConfigureDefaultsDocument: { [key: string]: unknown };
    const ConfigureDlnaDocument: { [key: string]: unknown };
    const ConfigureGeneralDocument: { [key: string]: unknown };
    const ConfigureInterfaceDocument: { [key: string]: unknown };
    const ConfigurePluginDocument: { [key: string]: unknown };
    const ConfigureScrapingDocument: { [key: string]: unknown };
    const ConfigureUiDocument: { [key: string]: unknown };
    const CriterionModifier: { [key: string]: unknown };
    const DeleteFilesDocument: { [key: string]: unknown };
    const DestroySavedFilterDocument: { [key: string]: unknown };
    const DirectoryDocument: { [key: string]: unknown };
    const DisableDlnaDocument: { [key: string]: unknown };
    const DlnaStatusDocument: { [key: string]: unknown };
    const EnableDlnaDocument: { [key: string]: unknown };
    const ExportObjectsDocument: { [key: string]: unknown };
    const FilterMode: { [key: string]: unknown };
    const FindDuplicateScenesDocument: { [key: string]: unknown };
    const FindGalleriesDocument: { [key: string]: unknown };
    const FindGalleriesForSelectDocument: { [key: string]: unknown };
    const FindGalleryDocument: { [key: string]: unknown };
    const FindImageDocument: { [key: string]: unknown };
    const FindImagesDocument: { [key: string]: unknown };
    const FindJobDocument: { [key: string]: unknown };
    const FindGroupDocument: { [key: string]: unknown };
    const FindGroupsDocument: { [key: string]: unknown };
    const FindGroupsForSelectDocument: { [key: string]: unknown };
    const FindPerformerDocument: { [key: string]: unknown };
    const FindPerformersDocument: { [key: string]: unknown };
    const FindPerformersForSelectDocument: { [key: string]: unknown };
    const FindSavedFilterDocument: { [key: string]: unknown };
    const FindSavedFiltersDocument: { [key: string]: unknown };
    const FindSceneDocument: { [key: string]: unknown };
    const FindSceneMarkerTagsDocument: { [key: string]: unknown };
    const FindSceneMarkersDocument: { [key: string]: unknown };
    const FindScenesByPathRegexDocument: { [key: string]: unknown };
    const FindScenesDocument: { [key: string]: unknown };
    const FindStudioDocument: { [key: string]: unknown };
    const FindStudiosDocument: { [key: string]: unknown };
    const FindStudiosForSelectDocument: { [key: string]: unknown };
    const FindTagDocument: { [key: string]: unknown };
    const FindTagsDocument: { [key: string]: unknown };
    const FindTagsForSelectDocument: { [key: string]: unknown };
    const FolderDataFragmentDoc: { [key: string]: unknown };
    const GalleriesUpdateDocument: { [key: string]: unknown };
    const GalleryChapterCreateDocument: { [key: string]: unknown };
    const GalleryChapterDataFragmentDoc: { [key: string]: unknown };
    const GalleryChapterDestroyDocument: { [key: string]: unknown };
    const GalleryChapterUpdateDocument: { [key: string]: unknown };
    const GalleryCreateDocument: { [key: string]: unknown };
    const GalleryDataFragmentDoc: { [key: string]: unknown };
    const GalleryDestroyDocument: { [key: string]: unknown };
    const GalleryFileDataFragmentDoc: { [key: string]: unknown };
    const GalleryUpdateDocument: { [key: string]: unknown };
    const GenderEnum: { [key: string]: unknown };
    const GenerateApiKeyDocument: { [key: string]: unknown };
    const HashAlgorithm: { [key: string]: unknown };
    const IdentifyFieldOptionsDataFragmentDoc: { [key: string]: unknown };
    const IdentifyFieldStrategy: { [key: string]: unknown };
    const IdentifyMetadataOptionsDataFragmentDoc: { [key: string]: unknown };
    const ImageDataFragmentDoc: { [key: string]: unknown };
    const ImageDecrementODocument: { [key: string]: unknown };
    const ImageDestroyDocument: { [key: string]: unknown };
    const ImageFileDataFragmentDoc: { [key: string]: unknown };
    const ImageIncrementODocument: { [key: string]: unknown };
    const ImageLightboxDisplayMode: { [key: string]: unknown };
    const ImageLightboxScrollMode: { [key: string]: unknown };
    const ImageResetODocument: { [key: string]: unknown };
    const ImageUpdateDocument: { [key: string]: unknown };
    const ImagesDestroyDocument: { [key: string]: unknown };
    const ImagesUpdateDocument: { [key: string]: unknown };
    const ImportDuplicateEnum: { [key: string]: unknown };
    const ImportMissingRefEnum: { [key: string]: unknown };
    const ImportObjectsDocument: { [key: string]: unknown };
    const InstallPluginPackagesDocument: { [key: string]: unknown };
    const InstallScraperPackagesDocument: { [key: string]: unknown };
    const InstalledPluginPackagesDocument: { [key: string]: unknown };
    const InstalledPluginPackagesStatusDocument: { [key: string]: unknown };
    const InstalledScraperPackagesDocument: { [key: string]: unknown };
    const InstalledScraperPackagesStatusDocument: { [key: string]: unknown };
    const JobDataFragmentDoc: { [key: string]: unknown };
    const JobQueueDocument: { [key: string]: unknown };
    const JobStatus: { [key: string]: unknown };
    const JobStatusUpdateType: { [key: string]: unknown };
    const JobsSubscribeDocument: { [key: string]: unknown };
    const LatestVersionDocument: { [key: string]: unknown };
    const ListGalleryScrapersDocument: { [key: string]: unknown };
    const ListGroupScrapersDocument: { [key: string]: unknown };
    const ListPerformerScrapersDocument: { [key: string]: unknown };
    const ListSceneScrapersDocument: { [key: string]: unknown };
    const LogEntryDataFragmentDoc: { [key: string]: unknown };
    const LogLevel: { [key: string]: unknown };
    const LoggingSubscribeDocument: { [key: string]: unknown };
    const LogsDocument: { [key: string]: unknown };
    const MarkerStringsDocument: { [key: string]: unknown };
    const MarkerWallDocument: { [key: string]: unknown };
    const MetadataAutoTagDocument: { [key: string]: unknown };
    const MetadataCleanDocument: { [key: string]: unknown };
    const MetadataExportDocument: { [key: string]: unknown };
    const MetadataGenerateDocument: { [key: string]: unknown };
    const MetadataIdentifyDocument: { [key: string]: unknown };
    const MetadataImportDocument: { [key: string]: unknown };
    const MetadataScanDocument: { [key: string]: unknown };
    const MigrateBlobsDocument: { [key: string]: unknown };
    const MigrateDocument: { [key: string]: unknown };
    const MigrateHashNamingDocument: { [key: string]: unknown };
    const MigrateSceneScreenshotsDocument: { [key: string]: unknown };
    const GroupCreateDocument: { [key: string]: unknown };
    const GroupDataFragmentDoc: { [key: string]: unknown };
    const GroupDestroyDocument: { [key: string]: unknown };
    const GroupUpdateDocument: { [key: string]: unknown };
    const GroupsDestroyDocument: { [key: string]: unknown };
    const OptimiseDatabaseDocument: { [key: string]: unknown };
    const OrientationEnum: { [key: string]: unknown };
    const PackageDataFragmentDoc: { [key: string]: unknown };
    const PackageType: { [key: string]: unknown };
    const ParseSceneFilenamesDocument: { [key: string]: unknown };
    const PerformerCreateDocument: { [key: string]: unknown };
    const PerformerDataFragmentDoc: { [key: string]: unknown };
    const PerformerDestroyDocument: { [key: string]: unknown };
    const PerformerUpdateDocument: { [key: string]: unknown };
    const PerformersDestroyDocument: { [key: string]: unknown };
    const PluginSettingTypeEnum: { [key: string]: unknown };
    const PluginTasksDocument: { [key: string]: unknown };
    const PluginsDocument: { [key: string]: unknown };
    const PreviewPreset: { [key: string]: unknown };
    const ReloadPluginsDocument: { [key: string]: unknown };
    const ReloadScrapersDocument: { [key: string]: unknown };
    const RemoveGalleryImagesDocument: { [key: string]: unknown };
    const RemoveTempDlnaipDocument: { [key: string]: unknown };
    const ResolutionEnum: { [key: string]: unknown };
    const RunPluginTaskDocument: { [key: string]: unknown };
    const SaveFilterDocument: { [key: string]: unknown };
    const SavedFilterDataFragmentDoc: { [key: string]: unknown };
    const ScanCompleteSubscribeDocument: { [key: string]: unknown };
    const SceneAssignFileDocument: { [key: string]: unknown };
    const SceneCreateDocument: { [key: string]: unknown };
    const SceneDataFragmentDoc: { [key: string]: unknown };
    const SceneDecrementODocument: { [key: string]: unknown };
    const SceneDestroyDocument: { [key: string]: unknown };
    const SceneGenerateScreenshotDocument: { [key: string]: unknown };
    const SceneIncrementODocument: { [key: string]: unknown };
    const SceneIncrementPlayCountDocument: { [key: string]: unknown };
    const SceneMarkerCreateDocument: { [key: string]: unknown };
    const SceneMarkerDataFragmentDoc: { [key: string]: unknown };
    const SceneMarkerDestroyDocument: { [key: string]: unknown };
    const SceneMarkerUpdateDocument: { [key: string]: unknown };
    const SceneMergeDocument: { [key: string]: unknown };
    const SceneResetODocument: { [key: string]: unknown };
    const SceneSaveActivityDocument: { [key: string]: unknown };
    const SceneStreamsDocument: { [key: string]: unknown };
    const SceneUpdateDocument: { [key: string]: unknown };
    const SceneWallDocument: { [key: string]: unknown };
    const ScenesDestroyDocument: { [key: string]: unknown };
    const ScenesUpdateDocument: { [key: string]: unknown };
    const ScrapeContentType: { [key: string]: unknown };
    const ScrapeGalleryUrlDocument: { [key: string]: unknown };
    const ScrapeGroupUrlDocument: { [key: string]: unknown };
    const ScrapeMultiPerformersDocument: { [key: string]: unknown };
    const ScrapeMultiScenesDocument: { [key: string]: unknown };
    const ScrapePerformerUrlDocument: { [key: string]: unknown };
    const ScrapeSceneUrlDocument: { [key: string]: unknown };
    const ScrapeSingleGalleryDocument: { [key: string]: unknown };
    const ScrapeSinglePerformerDocument: { [key: string]: unknown };
    const ScrapeSingleSceneDocument: { [key: string]: unknown };
    const ScrapeSingleStudioDocument: { [key: string]: unknown };
    const ScrapeType: { [key: string]: unknown };
    const ScrapedGalleryDataFragmentDoc: { [key: string]: unknown };
    const ScrapedGroupDataFragmentDoc: { [key: string]: unknown };
    const ScrapedGroupStudioDataFragmentDoc: { [key: string]: unknown };
    const ScrapedPerformerDataFragmentDoc: { [key: string]: unknown };
    const ScrapedSceneDataFragmentDoc: { [key: string]: unknown };
    const ScrapedSceneGroupDataFragmentDoc: { [key: string]: unknown };
    const ScrapedScenePerformerDataFragmentDoc: { [key: string]: unknown };
    const ScrapedSceneStudioDataFragmentDoc: { [key: string]: unknown };
    const ScrapedSceneTagDataFragmentDoc: { [key: string]: unknown };
    const ScrapedStashBoxPerformerDataFragmentDoc: { [key: string]: unknown };
    const ScrapedStashBoxSceneDataFragmentDoc: { [key: string]: unknown };
    const ScrapedStudioDataFragmentDoc: { [key: string]: unknown };
    const ScraperSourceDataFragmentDoc: { [key: string]: unknown };
    const SelectGalleryDataFragmentDoc: { [key: string]: unknown };
    const SelectGroupDataFragmentDoc: { [key: string]: unknown };
    const SelectPerformerDataFragmentDoc: { [key: string]: unknown };
    const SelectStudioDataFragmentDoc: { [key: string]: unknown };
    const SelectTagDataFragmentDoc: { [key: string]: unknown };
    const SetPluginsEnabledDocument: { [key: string]: unknown };
    const SetupDocument: { [key: string]: unknown };
    const SlimGalleryDataFragmentDoc: { [key: string]: unknown };
    const SlimImageDataFragmentDoc: { [key: string]: unknown };
    const SlimGroupDataFragmentDoc: { [key: string]: unknown };
    const SlimPerformerDataFragmentDoc: { [key: string]: unknown };
    const SlimSceneDataFragmentDoc: { [key: string]: unknown };
    const SlimStudioDataFragmentDoc: { [key: string]: unknown };
    const SlimTagDataFragmentDoc: { [key: string]: unknown };
    const SortDirectionEnum: { [key: string]: unknown };
    const StashBoxBatchPerformerTagDocument: { [key: string]: unknown };
    const StashBoxBatchStudioTagDocument: { [key: string]: unknown };
    const StatsDocument: { [key: string]: unknown };
    const StopAllJobsDocument: { [key: string]: unknown };
    const StopJobDocument: { [key: string]: unknown };
    const StreamingResolutionEnum: { [key: string]: unknown };
    const StudioCreateDocument: { [key: string]: unknown };
    const StudioDataFragmentDoc: { [key: string]: unknown };
    const StudioDestroyDocument: { [key: string]: unknown };
    const StudioUpdateDocument: { [key: string]: unknown };
    const StudiosDestroyDocument: { [key: string]: unknown };
    const SubmitStashBoxFingerprintsDocument: { [key: string]: unknown };
    const SubmitStashBoxPerformerDraftDocument: { [key: string]: unknown };
    const SubmitStashBoxSceneDraftDocument: { [key: string]: unknown };
    const SystemStatusDocument: { [key: string]: unknown };
    const SystemStatusEnum: { [key: string]: unknown };
    const TagCreateDocument: { [key: string]: unknown };
    const TagDataFragmentDoc: { [key: string]: unknown };
    const TagDestroyDocument: { [key: string]: unknown };
    const TagUpdateDocument: { [key: string]: unknown };
    const TagsDestroyDocument: { [key: string]: unknown };
    const TagsMergeDocument: { [key: string]: unknown };
    const UninstallPluginPackagesDocument: { [key: string]: unknown };
    const UninstallScraperPackagesDocument: { [key: string]: unknown };
    const UpdatePluginPackagesDocument: { [key: string]: unknown };
    const UpdateScraperPackagesDocument: { [key: string]: unknown };
    const ValidateStashBoxDocument: { [key: string]: unknown };
    const VersionDocument: { [key: string]: unknown };
    const VideoFileDataFragmentDoc: { [key: string]: unknown };
    const VisualFileDataFragmentDoc: { [key: string]: unknown };
    function refetchAvailablePluginPackagesQuery(...args: unknown[]): unknown;
    function refetchAvailableScraperPackagesQuery(...args: unknown[]): unknown;
    function refetchConfigurationQuery(...args: unknown[]): unknown;
    function refetchDirectoryQuery(...args: unknown[]): unknown;
    function refetchDlnaStatusQuery(...args: unknown[]): unknown;
    function refetchFindDuplicateScenesQuery(...args: unknown[]): unknown;
    function refetchFindGalleriesForSelectQuery(...args: unknown[]): unknown;
    function refetchFindGalleriesQuery(...args: unknown[]): unknown;
    function refetchFindGalleryQuery(...args: unknown[]): unknown;
    function refetchFindImageQuery(...args: unknown[]): unknown;
    function refetchFindImagesQuery(...args: unknown[]): unknown;
    function refetchFindJobQuery(...args: unknown[]): unknown;
    function refetchFindGroupQuery(...args: unknown[]): unknown;
    function refetchFindGroupsForSelectQuery(...args: unknown[]): unknown;
    function refetchFindGroupsQuery(...args: unknown[]): unknown;
    function refetchFindPerformerQuery(...args: unknown[]): unknown;
    function refetchFindPerformersForSelectQuery(...args: unknown[]): unknown;
    function refetchFindPerformersQuery(...args: unknown[]): unknown;
    function refetchFindSavedFilterQuery(...args: unknown[]): unknown;
    function refetchFindSavedFiltersQuery(...args: unknown[]): unknown;
    function refetchFindSceneMarkerTagsQuery(...args: unknown[]): unknown;
    function refetchFindSceneMarkersQuery(...args: unknown[]): unknown;
    function refetchFindSceneQuery(...args: unknown[]): unknown;
    function refetchFindScenesByPathRegexQuery(...args: unknown[]): unknown;
    function refetchFindScenesQuery(...args: unknown[]): unknown;
    function refetchFindStudioQuery(...args: unknown[]): unknown;
    function refetchFindStudiosForSelectQuery(...args: unknown[]): unknown;
    function refetchFindStudiosQuery(...args: unknown[]): unknown;
    function refetchFindTagQuery(...args: unknown[]): unknown;
    function refetchFindTagsForSelectQuery(...args: unknown[]): unknown;
    function refetchFindTagsQuery(...args: unknown[]): unknown;
    function refetchInstalledPluginPackagesQuery(...args: unknown[]): unknown;
    function refetchInstalledPluginPackagesStatusQuery(
      ...args: unknown[]
    ): unknown;
    function refetchInstalledScraperPackagesQuery(...args: unknown[]): unknown;
    function refetchInstalledScraperPackagesStatusQuery(
      ...args: unknown[]
    ): unknown;
    function refetchJobQueueQuery(...args: unknown[]): unknown;
    function refetchLatestVersionQuery(...args: unknown[]): unknown;
    function refetchListGalleryScrapersQuery(...args: unknown[]): unknown;
    function refetchListGroupScrapersQuery(...args: unknown[]): unknown;
    function refetchListPerformerScrapersQuery(...args: unknown[]): unknown;
    function refetchListSceneScrapersQuery(...args: unknown[]): unknown;
    function refetchLogsQuery(...args: unknown[]): unknown;
    function refetchMarkerStringsQuery(...args: unknown[]): unknown;
    function refetchMarkerWallQuery(...args: unknown[]): unknown;
    function refetchParseSceneFilenamesQuery(...args: unknown[]): unknown;
    function refetchPluginTasksQuery(...args: unknown[]): unknown;
    function refetchPluginsQuery(...args: unknown[]): unknown;
    function refetchSceneStreamsQuery(...args: unknown[]): unknown;
    function refetchSceneWallQuery(...args: unknown[]): unknown;
    function refetchScrapeGalleryUrlQuery(...args: unknown[]): unknown;
    function refetchScrapeGroupUrlQuery(...args: unknown[]): unknown;
    function refetchScrapeMultiPerformersQuery(...args: unknown[]): unknown;
    function refetchScrapeMultiScenesQuery(...args: unknown[]): unknown;
    function refetchScrapePerformerUrlQuery(...args: unknown[]): unknown;
    function refetchScrapeSceneUrlQuery(...args: unknown[]): unknown;
    function refetchScrapeSingleGalleryQuery(...args: unknown[]): unknown;
    function refetchScrapeSinglePerformerQuery(...args: unknown[]): unknown;
    function refetchScrapeSingleSceneQuery(...args: unknown[]): unknown;
    function refetchScrapeSingleStudioQuery(...args: unknown[]): unknown;
    function refetchStatsQuery(...args: unknown[]): unknown;
    function refetchSystemStatusQuery(...args: unknown[]): unknown;
    function refetchValidateStashBoxQuery(...args: unknown[]): unknown;
    function refetchVersionQuery(...args: unknown[]): unknown;
    function useAddGalleryImagesMutation(...args: unknown[]): unknown;
    function useAddTempDlnaipMutation(...args: unknown[]): unknown;
    function useAnonymiseDatabaseMutation(...args: unknown[]): unknown;
    function useAvailablePluginPackagesLazyQuery(...args: unknown[]): unknown;
    function useAvailablePluginPackagesQuery(...args: unknown[]): unknown;
    function useAvailablePluginPackagesSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useAvailableScraperPackagesLazyQuery(...args: unknown[]): unknown;
    function useAvailableScraperPackagesQuery(...args: unknown[]): unknown;
    function useAvailableScraperPackagesSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useBackupDatabaseMutation(...args: unknown[]): unknown;
    function useBulkGalleryUpdateMutation(...args: unknown[]): unknown;
    function useBulkImageUpdateMutation(...args: unknown[]): unknown;
    function useBulkGroupUpdateMutation(...args: unknown[]): unknown;
    function useBulkPerformerUpdateMutation(...args: unknown[]): unknown;
    function useBulkSceneUpdateMutation(...args: unknown[]): unknown;
    function useConfigurationLazyQuery(...args: unknown[]): unknown;
    function useConfigurationQuery(...args: unknown[]): unknown;
    function useConfigurationSuspenseQuery(...args: unknown[]): unknown;
    function useConfigureDefaultsMutation(...args: unknown[]): unknown;
    function useConfigureDlnaMutation(...args: unknown[]): unknown;
    function useConfigureGeneralMutation(...args: unknown[]): unknown;
    function useConfigureInterfaceMutation(...args: unknown[]): unknown;
    function useConfigurePluginMutation(...args: unknown[]): unknown;
    function useConfigureScrapingMutation(...args: unknown[]): unknown;
    function useConfigureUiMutation(...args: unknown[]): unknown;
    function useDeleteFilesMutation(...args: unknown[]): unknown;
    function useDestroySavedFilterMutation(...args: unknown[]): unknown;
    function useDirectoryLazyQuery(...args: unknown[]): unknown;
    function useDirectoryQuery(...args: unknown[]): unknown;
    function useDirectorySuspenseQuery(...args: unknown[]): unknown;
    function useDisableDlnaMutation(...args: unknown[]): unknown;
    function useDlnaStatusLazyQuery(...args: unknown[]): unknown;
    function useDlnaStatusQuery(...args: unknown[]): unknown;
    function useDlnaStatusSuspenseQuery(...args: unknown[]): unknown;
    function useEnableDlnaMutation(...args: unknown[]): unknown;
    function useExportObjectsMutation(...args: unknown[]): unknown;
    function useFindDuplicateScenesLazyQuery(...args: unknown[]): unknown;
    function useFindDuplicateScenesQuery(...args: unknown[]): unknown;
    function useFindDuplicateScenesSuspenseQuery(...args: unknown[]): unknown;
    function useFindGalleriesForSelectLazyQuery(...args: unknown[]): unknown;
    function useFindGalleriesForSelectQuery(...args: unknown[]): unknown;
    function useFindGalleriesForSelectSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useFindGalleriesLazyQuery(...args: unknown[]): unknown;
    function useFindGalleriesQuery(...args: unknown[]): unknown;
    function useFindGalleriesSuspenseQuery(...args: unknown[]): unknown;
    function useFindGalleryLazyQuery(...args: unknown[]): unknown;
    function useFindGalleryQuery(...args: unknown[]): unknown;
    function useFindGallerySuspenseQuery(...args: unknown[]): unknown;
    function useFindImageLazyQuery(...args: unknown[]): unknown;
    function useFindImageQuery(...args: unknown[]): unknown;
    function useFindImageSuspenseQuery(...args: unknown[]): unknown;
    function useFindImagesLazyQuery(...args: unknown[]): unknown;
    function useFindImagesQuery(...args: unknown[]): unknown;
    function useFindImagesSuspenseQuery(...args: unknown[]): unknown;
    function useFindJobLazyQuery(...args: unknown[]): unknown;
    function useFindJobQuery(...args: unknown[]): unknown;
    function useFindJobSuspenseQuery(...args: unknown[]): unknown;
    function useFindGroupLazyQuery(...args: unknown[]): unknown;
    function useFindGroupQuery(...args: unknown[]): unknown;
    function useFindGroupSuspenseQuery(...args: unknown[]): unknown;
    function useFindGroupsForSelectLazyQuery(...args: unknown[]): unknown;
    function useFindGroupsForSelectQuery(...args: unknown[]): unknown;
    function useFindGroupsForSelectSuspenseQuery(...args: unknown[]): unknown;
    function useFindGroupsLazyQuery(...args: unknown[]): unknown;
    function useFindGroupsQuery(...args: unknown[]): unknown;
    function useFindGroupsSuspenseQuery(...args: unknown[]): unknown;
    function useFindPerformerLazyQuery(...args: unknown[]): unknown;
    function useFindPerformerQuery(...args: unknown[]): unknown;
    function useFindPerformerSuspenseQuery(...args: unknown[]): unknown;
    function useFindPerformersForSelectLazyQuery(...args: unknown[]): unknown;
    function useFindPerformersForSelectQuery(...args: unknown[]): unknown;
    function useFindPerformersForSelectSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useFindPerformersLazyQuery(...args: unknown[]): unknown;
    function useFindPerformersQuery(...args: unknown[]): unknown;
    function useFindPerformersSuspenseQuery(...args: unknown[]): unknown;
    function useFindSavedFilterLazyQuery(...args: unknown[]): unknown;
    function useFindSavedFilterQuery(...args: unknown[]): unknown;
    function useFindSavedFilterSuspenseQuery(...args: unknown[]): unknown;
    function useFindSavedFiltersLazyQuery(...args: unknown[]): unknown;
    function useFindSavedFiltersQuery(...args: unknown[]): unknown;
    function useFindSavedFiltersSuspenseQuery(...args: unknown[]): unknown;
    function useFindSceneLazyQuery(...args: unknown[]): unknown;
    function useFindSceneMarkerTagsLazyQuery(...args: unknown[]): unknown;
    function useFindSceneMarkerTagsQuery(...args: unknown[]): unknown;
    function useFindSceneMarkerTagsSuspenseQuery(...args: unknown[]): unknown;
    function useFindSceneMarkersLazyQuery(...args: unknown[]): unknown;
    function useFindSceneMarkersQuery(...args: unknown[]): unknown;
    function useFindSceneMarkersSuspenseQuery(...args: unknown[]): unknown;
    function useFindSceneQuery(...args: unknown[]): unknown;
    function useFindSceneSuspenseQuery(...args: unknown[]): unknown;
    function useFindScenesByPathRegexLazyQuery(...args: unknown[]): unknown;
    function useFindScenesByPathRegexQuery(...args: unknown[]): unknown;
    function useFindScenesByPathRegexSuspenseQuery(...args: unknown[]): unknown;
    function useFindScenesLazyQuery(...args: unknown[]): unknown;
    function useFindScenesQuery(...args: unknown[]): unknown;
    function useFindScenesSuspenseQuery(...args: unknown[]): unknown;
    function useFindStudioLazyQuery(...args: unknown[]): unknown;
    function useFindStudioQuery(...args: unknown[]): unknown;
    function useFindStudioSuspenseQuery(...args: unknown[]): unknown;
    function useFindStudiosForSelectLazyQuery(...args: unknown[]): unknown;
    function useFindStudiosForSelectQuery(...args: unknown[]): unknown;
    function useFindStudiosForSelectSuspenseQuery(...args: unknown[]): unknown;
    function useFindStudiosLazyQuery(...args: unknown[]): unknown;
    function useFindStudiosQuery(...args: unknown[]): unknown;
    function useFindStudiosSuspenseQuery(...args: unknown[]): unknown;
    function useFindTagLazyQuery(...args: unknown[]): unknown;
    function useFindTagQuery(...args: unknown[]): unknown;
    function useFindTagSuspenseQuery(...args: unknown[]): unknown;
    function useFindTagsForSelectLazyQuery(...args: unknown[]): unknown;
    function useFindTagsForSelectQuery(...args: unknown[]): unknown;
    function useFindTagsForSelectSuspenseQuery(...args: unknown[]): unknown;
    function useFindTagsLazyQuery(...args: unknown[]): unknown;
    function useFindTagsQuery(...args: unknown[]): unknown;
    function useFindTagsSuspenseQuery(...args: unknown[]): unknown;
    function useGalleriesUpdateMutation(...args: unknown[]): unknown;
    function useGalleryChapterCreateMutation(...args: unknown[]): unknown;
    function useGalleryChapterDestroyMutation(...args: unknown[]): unknown;
    function useGalleryChapterUpdateMutation(...args: unknown[]): unknown;
    function useGalleryCreateMutation(...args: unknown[]): unknown;
    function useGalleryDestroyMutation(...args: unknown[]): unknown;
    function useGalleryUpdateMutation(...args: unknown[]): unknown;
    function useGenerateApiKeyMutation(...args: unknown[]): unknown;
    function useImageDecrementOMutation(...args: unknown[]): unknown;
    function useImageDestroyMutation(...args: unknown[]): unknown;
    function useImageIncrementOMutation(...args: unknown[]): unknown;
    function useImageResetOMutation(...args: unknown[]): unknown;
    function useImageUpdateMutation(...args: unknown[]): unknown;
    function useImagesDestroyMutation(...args: unknown[]): unknown;
    function useImagesUpdateMutation(...args: unknown[]): unknown;
    function useImportObjectsMutation(...args: unknown[]): unknown;
    function useInstallPluginPackagesMutation(...args: unknown[]): unknown;
    function useInstallScraperPackagesMutation(...args: unknown[]): unknown;
    function useInstalledPluginPackagesLazyQuery(...args: unknown[]): unknown;
    function useInstalledPluginPackagesQuery(...args: unknown[]): unknown;
    function useInstalledPluginPackagesStatusLazyQuery(
      ...args: unknown[]
    ): unknown;
    function useInstalledPluginPackagesStatusQuery(...args: unknown[]): unknown;
    function useInstalledPluginPackagesStatusSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useInstalledPluginPackagesSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useInstalledScraperPackagesLazyQuery(...args: unknown[]): unknown;
    function useInstalledScraperPackagesQuery(...args: unknown[]): unknown;
    function useInstalledScraperPackagesStatusLazyQuery(
      ...args: unknown[]
    ): unknown;
    function useInstalledScraperPackagesStatusQuery(
      ...args: unknown[]
    ): unknown;
    function useInstalledScraperPackagesStatusSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useInstalledScraperPackagesSuspenseQuery(
      ...args: unknown[]
    ): unknown;
    function useJobQueueLazyQuery(...args: unknown[]): unknown;
    function useJobQueueQuery(...args: unknown[]): unknown;
    function useJobQueueSuspenseQuery(...args: unknown[]): unknown;
    function useJobsSubscribeSubscription(...args: unknown[]): unknown;
    function useLatestVersionLazyQuery(...args: unknown[]): unknown;
    function useLatestVersionQuery(...args: unknown[]): unknown;
    function useLatestVersionSuspenseQuery(...args: unknown[]): unknown;
    function useListGalleryScrapersLazyQuery(...args: unknown[]): unknown;
    function useListGalleryScrapersQuery(...args: unknown[]): unknown;
    function useListGalleryScrapersSuspenseQuery(...args: unknown[]): unknown;
    function useListGroupScrapersLazyQuery(...args: unknown[]): unknown;
    function useListGroupScrapersQuery(...args: unknown[]): unknown;
    function useListGroupScrapersSuspenseQuery(...args: unknown[]): unknown;
    function useListPerformerScrapersLazyQuery(...args: unknown[]): unknown;
    function useListPerformerScrapersQuery(...args: unknown[]): unknown;
    function useListPerformerScrapersSuspenseQuery(...args: unknown[]): unknown;
    function useListSceneScrapersLazyQuery(...args: unknown[]): unknown;
    function useListSceneScrapersQuery(...args: unknown[]): unknown;
    function useListSceneScrapersSuspenseQuery(...args: unknown[]): unknown;
    function useLoggingSubscribeSubscription(...args: unknown[]): unknown;
    function useLogsLazyQuery(...args: unknown[]): unknown;
    function useLogsQuery(...args: unknown[]): unknown;
    function useLogsSuspenseQuery(...args: unknown[]): unknown;
    function useMarkerStringsLazyQuery(...args: unknown[]): unknown;
    function useMarkerStringsQuery(...args: unknown[]): unknown;
    function useMarkerStringsSuspenseQuery(...args: unknown[]): unknown;
    function useMarkerWallLazyQuery(...args: unknown[]): unknown;
    function useMarkerWallQuery(...args: unknown[]): unknown;
    function useMarkerWallSuspenseQuery(...args: unknown[]): unknown;
    function useMetadataAutoTagMutation(...args: unknown[]): unknown;
    function useMetadataCleanMutation(...args: unknown[]): unknown;
    function useMetadataExportMutation(...args: unknown[]): unknown;
    function useMetadataGenerateMutation(...args: unknown[]): unknown;
    function useMetadataIdentifyMutation(...args: unknown[]): unknown;
    function useMetadataImportMutation(...args: unknown[]): unknown;
    function useMetadataScanMutation(...args: unknown[]): unknown;
    function useMigrateBlobsMutation(...args: unknown[]): unknown;
    function useMigrateHashNamingMutation(...args: unknown[]): unknown;
    function useMigrateMutation(...args: unknown[]): unknown;
    function useMigrateSceneScreenshotsMutation(...args: unknown[]): unknown;
    function useGroupCreateMutation(...args: unknown[]): unknown;
    function useGroupDestroyMutation(...args: unknown[]): unknown;
    function useGroupUpdateMutation(...args: unknown[]): unknown;
    function useGroupsDestroyMutation(...args: unknown[]): unknown;
    function useOptimiseDatabaseMutation(...args: unknown[]): unknown;
    function useParseSceneFilenamesLazyQuery(...args: unknown[]): unknown;
    function useParseSceneFilenamesQuery(...args: unknown[]): unknown;
    function useParseSceneFilenamesSuspenseQuery(...args: unknown[]): unknown;
    function usePerformerCreateMutation(...args: unknown[]): unknown;
    function usePerformerDestroyMutation(...args: unknown[]): unknown;
    function usePerformerUpdateMutation(...args: unknown[]): unknown;
    function usePerformersDestroyMutation(...args: unknown[]): unknown;
    function usePluginTasksLazyQuery(...args: unknown[]): unknown;
    function usePluginTasksQuery(...args: unknown[]): unknown;
    function usePluginTasksSuspenseQuery(...args: unknown[]): unknown;
    function usePluginsLazyQuery(...args: unknown[]): unknown;
    function usePluginsQuery(...args: unknown[]): unknown;
    function usePluginsSuspenseQuery(...args: unknown[]): unknown;
    function useReloadPluginsMutation(...args: unknown[]): unknown;
    function useReloadScrapersMutation(...args: unknown[]): unknown;
    function useRemoveGalleryImagesMutation(...args: unknown[]): unknown;
    function useRemoveTempDlnaipMutation(...args: unknown[]): unknown;
    function useRunPluginTaskMutation(...args: unknown[]): unknown;
    function useSaveFilterMutation(...args: unknown[]): unknown;
    function useScanCompleteSubscribeSubscription(...args: unknown[]): unknown;
    function useSceneAssignFileMutation(...args: unknown[]): unknown;
    function useSceneCreateMutation(...args: unknown[]): unknown;
    function useSceneDecrementOMutation(...args: unknown[]): unknown;
    function useSceneDestroyMutation(...args: unknown[]): unknown;
    function useSceneGenerateScreenshotMutation(...args: unknown[]): unknown;
    function useSceneIncrementOMutation(...args: unknown[]): unknown;
    function useSceneIncrementPlayCountMutation(...args: unknown[]): unknown;
    function useSceneMarkerCreateMutation(...args: unknown[]): unknown;
    function useSceneMarkerDestroyMutation(...args: unknown[]): unknown;
    function useSceneMarkerUpdateMutation(...args: unknown[]): unknown;
    function useSceneMergeMutation(...args: unknown[]): unknown;
    function useSceneResetOMutation(...args: unknown[]): unknown;
    function useSceneSaveActivityMutation(...args: unknown[]): unknown;
    function useSceneStreamsLazyQuery(...args: unknown[]): unknown;
    function useSceneStreamsQuery(...args: unknown[]): unknown;
    function useSceneStreamsSuspenseQuery(...args: unknown[]): unknown;
    function useSceneUpdateMutation(...args: unknown[]): unknown;
    function useSceneWallLazyQuery(...args: unknown[]): unknown;
    function useSceneWallQuery(...args: unknown[]): unknown;
    function useSceneWallSuspenseQuery(...args: unknown[]): unknown;
    function useScenesDestroyMutation(...args: unknown[]): unknown;
    function useScenesUpdateMutation(...args: unknown[]): unknown;
    function useScrapeGalleryUrlLazyQuery(...args: unknown[]): unknown;
    function useScrapeGalleryUrlQuery(...args: unknown[]): unknown;
    function useScrapeGalleryUrlSuspenseQuery(...args: unknown[]): unknown;
    function useScrapeGroupUrlLazyQuery(...args: unknown[]): unknown;
    function useScrapeGroupUrlQuery(...args: unknown[]): unknown;
    function useScrapeGroupUrlSuspenseQuery(...args: unknown[]): unknown;
    function useScrapeMultiPerformersLazyQuery(...args: unknown[]): unknown;
    function useScrapeMultiPerformersQuery(...args: unknown[]): unknown;
    function useScrapeMultiPerformersSuspenseQuery(...args: unknown[]): unknown;
    function useScrapeMultiScenesLazyQuery(...args: unknown[]): unknown;
    function useScrapeMultiScenesQuery(...args: unknown[]): unknown;
    function useScrapeMultiScenesSuspenseQuery(...args: unknown[]): unknown;
    function useScrapePerformerUrlLazyQuery(...args: unknown[]): unknown;
    function useScrapePerformerUrlQuery(...args: unknown[]): unknown;
    function useScrapePerformerUrlSuspenseQuery(...args: unknown[]): unknown;
    function useScrapeSceneUrlLazyQuery(...args: unknown[]): unknown;
    function useScrapeSceneUrlQuery(...args: unknown[]): unknown;
    function useScrapeSceneUrlSuspenseQuery(...args: unknown[]): unknown;
    function useScrapeSingleGalleryLazyQuery(...args: unknown[]): unknown;
    function useScrapeSingleGalleryQuery(...args: unknown[]): unknown;
    function useScrapeSingleGallerySuspenseQuery(...args: unknown[]): unknown;
    function useScrapeSinglePerformerLazyQuery(...args: unknown[]): unknown;
    function useScrapeSinglePerformerQuery(...args: unknown[]): unknown;
    function useScrapeSinglePerformerSuspenseQuery(...args: unknown[]): unknown;
    function useScrapeSingleSceneLazyQuery(...args: unknown[]): unknown;
    function useScrapeSingleSceneQuery(...args: unknown[]): unknown;
    function useScrapeSingleSceneSuspenseQuery(...args: unknown[]): unknown;
    function useScrapeSingleStudioLazyQuery(...args: unknown[]): unknown;
    function useScrapeSingleStudioQuery(...args: unknown[]): unknown;
    function useScrapeSingleStudioSuspenseQuery(...args: unknown[]): unknown;
    function useSetDefaultFilterMutation(...args: unknown[]): unknown;
    function useSetPluginsEnabledMutation(...args: unknown[]): unknown;
    function useSetupMutation(...args: unknown[]): unknown;
    function useStashBoxBatchPerformerTagMutation(...args: unknown[]): unknown;
    function useStashBoxBatchStudioTagMutation(...args: unknown[]): unknown;
    function useStatsLazyQuery(...args: unknown[]): unknown;
    function useStatsQuery(...args: unknown[]): unknown;
    function useStatsSuspenseQuery(...args: unknown[]): unknown;
    function useStopAllJobsMutation(...args: unknown[]): unknown;
    function useStopJobMutation(...args: unknown[]): unknown;
    function useStudioCreateMutation(...args: unknown[]): unknown;
    function useStudioDestroyMutation(...args: unknown[]): unknown;
    function useStudioUpdateMutation(...args: unknown[]): unknown;
    function useStudiosDestroyMutation(...args: unknown[]): unknown;
    function useSubmitStashBoxFingerprintsMutation(...args: unknown[]): unknown;
    function useSubmitStashBoxPerformerDraftMutation(
      ...args: unknown[]
    ): unknown;
    function useSubmitStashBoxSceneDraftMutation(...args: unknown[]): unknown;
    function useSystemStatusLazyQuery(...args: unknown[]): unknown;
    function useSystemStatusQuery(...args: unknown[]): unknown;
    function useSystemStatusSuspenseQuery(...args: unknown[]): unknown;
    function useTagCreateMutation(...args: unknown[]): unknown;
    function useTagDestroyMutation(...args: unknown[]): unknown;
    function useTagUpdateMutation(...args: unknown[]): unknown;
    function useTagsDestroyMutation(...args: unknown[]): unknown;
    function useTagsMergeMutation(...args: unknown[]): unknown;
    function useUninstallPluginPackagesMutation(...args: unknown[]): unknown;
    function useUninstallScraperPackagesMutation(...args: unknown[]): unknown;
    function useUpdatePluginPackagesMutation(...args: unknown[]): unknown;
    function useUpdateScraperPackagesMutation(...args: unknown[]): unknown;
    function useValidateStashBoxLazyQuery(...args: unknown[]): unknown;
    function useValidateStashBoxQuery(...args: unknown[]): unknown;
    function useValidateStashBoxSuspenseQuery(...args: unknown[]): unknown;
    function useVersionLazyQuery(...args: unknown[]): unknown;
    function useVersionQuery(...args: unknown[]): unknown;
    function useVersionSuspenseQuery(...args: unknown[]): unknown;
  }
  namespace libraries {
    const Apollo: typeof import("@apollo/client");
    const Bootstrap: typeof import("react-bootstrap");
    const FontAwesomeRegular: typeof import("@fortawesome/free-regular-svg-icons");
    const FontAwesomeSolid: typeof import("@fortawesome/free-solid-svg-icons");
    const Intl: typeof import("react-intl");
    const Mousetrap: typeof import("mousetrap");

    import { MousetrapStatic } from "mousetrap";
    function MousetrapPause(mousetrap: MousetrapStatic): MousetrapStatic;

    const ReactRouterDOM: typeof import("react-router-dom");
  }
  namespace loadableComponents {
    interface ISceneCardProps {
      scene: unknown;
      containerWidth?: number;
      previewHeight?: number;
      index?: number;
      queue?: unknown;
      compact?: boolean;
      selecting?: boolean;
      selected?: boolean | undefined;
      zoomIndex?: number;
      onSelectedChanged?: (selected: boolean, shiftKey: boolean) => void;
    }
    interface IScenePreviewProps {
      isPortrait: boolean;
      image?: string;
      video?: string;
      soundActive: boolean;
      vttPath?: string;
      onScrubberClick?: (timestamp: number) => void;
    }
    function SceneCard(): Promise<{
      SceneCard: React.FC<ISceneCardProps>;
      ScenePreview: React.FC<IScenePreviewProps>;
    }>;
  }
  const components: {
    HoverPopover: React.FC<unknown>;
    TagLink: React.FC<unknown>;
    LoadingIndicator: React.FC<unknown>;
    Icon: React.FC<unknown>;
    "MainNavBar.MenuItems": React.FC<unknown>;
    "MainNavBar.UtilityItems": React.FC<unknown>;
    PerformerSelect: React.FC<unknown>;
    PerformerIDSelect: React.FC<unknown>;
    TagSelect: React.FC<unknown>;
    TagIDSelect: React.FC<unknown>;
    StudioSelect: React.FC<unknown>;
    StudioIDSelect: React.FC<unknown>;
    GallerySelect: React.FC<unknown>;
    GalleryIDSelect: React.FC<unknown>;
    GroupSelect: React.FC<unknown>;
    GroupIDSelect: React.FC<unknown>;
    SceneSelect: React.FC<unknown>;
    SceneIDSelect: React.FC<unknown>;
    DateInput: React.FC<unknown>;
    CountrySelect: React.FC<unknown>;
    FolderSelect: React.FC<unknown>;
    "SceneCard.Popovers": React.FC<unknown>;
    "SceneCard.Details": React.FC<unknown>;
    "SceneCard.Overlays": React.FC<unknown>;
    "SceneCard.Image": React.FC<unknown>;
    PluginSettings: React.FC<unknown>;
    Setting: React.FC<unknown>;
    SettingGroup: React.FC<unknown>;
    BooleanSetting: React.FC<unknown>;
    SelectSetting: React.FC<unknown>;
    ChangeButtonSetting: React.FC<unknown>;
    SettingModal: React.FC<unknown>;
    ModalSetting: React.FC<unknown>;
    StringSetting: React.FC<unknown>;
    NumberSetting: React.FC<unknown>;
    StringListSetting: React.FC<unknown>;
    ConstantSetting: React.FC<unknown>;
    SceneFileInfoPanel: React.FC<unknown>;
  };
  type PatchableComponentNames = keyof typeof components | string;
  namespace utils {
    namespace NavUtils {
      function makePerformerScenesUrl(...args: unknown[]): unknown;
      function makePerformerImagesUrl(...args: unknown[]): unknown;
      function makePerformerGalleriesUrl(...args: unknown[]): unknown;
      function makePerformerGroupsUrl(...args: unknown[]): unknown;
      function makePerformersCountryUrl(...args: unknown[]): unknown;
      function makeStudioScenesUrl(...args: unknown[]): unknown;
      function makeStudioImagesUrl(...args: unknown[]): unknown;
      function makeStudioGalleriesUrl(...args: unknown[]): unknown;
      function makeStudioGroupsUrl(...args: unknown[]): unknown;
      function makeStudioPerformersUrl(...args: unknown[]): unknown;
      function makeTagUrl(...args: unknown[]): unknown;
      function makeParentTagsUrl(...args: unknown[]): unknown;
      function makeChildTagsUrl(...args: unknown[]): unknown;
      function makeTagSceneMarkersUrl(...args: unknown[]): unknown;
      function makeTagScenesUrl(...args: unknown[]): unknown;
      function makeTagPerformersUrl(...args: unknown[]): unknown;
      function makeTagGalleriesUrl(...args: unknown[]): unknown;
      function makeTagImagesUrl(...args: unknown[]): unknown;
      function makeScenesPHashMatchUrl(...args: unknown[]): unknown;
      function makeSceneMarkerUrl(...args: unknown[]): unknown;
      function makeGroupScenesUrl(...args: unknown[]): unknown;
      function makeChildStudiosUrl(...args: unknown[]): unknown;
      function makeGalleryImagesUrl(...args: unknown[]): unknown;
    }
    namespace StashService {
      function evictQueries(...args: unknown[]): unknown;
      function getClient(...args: unknown[]): unknown;
      function mutateAddGalleryImages(...args: unknown[]): unknown;
      function mutateAnonymiseDatabase(...args: unknown[]): unknown;
      function mutateBackupDatabase(...args: unknown[]): unknown;
      function mutateCreateScene(...args: unknown[]): unknown;
      function mutateDeleteFiles(...args: unknown[]): unknown;
      function mutateExportObjects(...args: unknown[]): unknown;
      function mutateGallerySetPrimaryFile(...args: unknown[]): unknown;
      function mutateImageDecrementO(...args: unknown[]): unknown;
      function mutateImageIncrementO(...args: unknown[]): unknown;
      function mutateImageResetO(...args: unknown[]): unknown;
      function mutateImageSetPrimaryFile(...args: unknown[]): unknown;
      function mutateImportObjects(...args: unknown[]): unknown;
      function mutateInstallPluginPackages(...args: unknown[]): unknown;
      function mutateInstallScraperPackages(...args: unknown[]): unknown;
      function mutateMetadataAutoTag(...args: unknown[]): unknown;
      function mutateMetadataClean(...args: unknown[]): unknown;
      function mutateMetadataExport(...args: unknown[]): unknown;
      function mutateMetadataGenerate(...args: unknown[]): unknown;
      function mutateMetadataIdentify(...args: unknown[]): unknown;
      function mutateMetadataImport(...args: unknown[]): unknown;
      function mutateMetadataScan(...args: unknown[]): unknown;
      function mutateMigrate(...args: unknown[]): unknown;
      function mutateMigrateBlobs(...args: unknown[]): unknown;
      function mutateMigrateHashNaming(...args: unknown[]): unknown;
      function mutateMigrateSceneScreenshots(...args: unknown[]): unknown;
      function mutateOptimiseDatabase(...args: unknown[]): unknown;
      function mutateReloadPlugins(...args: unknown[]): unknown;
      function mutateReloadScrapers(...args: unknown[]): unknown;
      function mutateRemoveGalleryImages(...args: unknown[]): unknown;
      function mutateRunPluginTask(...args: unknown[]): unknown;
      function mutateSceneAssignFile(...args: unknown[]): unknown;
      function mutateSceneMerge(...args: unknown[]): unknown;
      function mutateSceneSetPrimaryFile(...args: unknown[]): unknown;
      function mutateSetPluginsEnabled(...args: unknown[]): unknown;
      function mutateSetup(...args: unknown[]): unknown;
      function mutateStashBoxBatchPerformerTag(...args: unknown[]): unknown;
      function mutateStashBoxBatchStudioTag(...args: unknown[]): unknown;
      function mutateStopJob(...args: unknown[]): unknown;
      function mutateSubmitStashBoxPerformerDraft(...args: unknown[]): unknown;
      function mutateSubmitStashBoxSceneDraft(...args: unknown[]): unknown;
      function mutateUninstallPluginPackages(...args: unknown[]): unknown;
      function mutateUninstallScraperPackages(...args: unknown[]): unknown;
      function mutateUpdatePluginPackages(...args: unknown[]): unknown;
      function mutateUpdateScraperPackages(...args: unknown[]): unknown;
      function queryAvailablePluginPackages(...args: unknown[]): unknown;
      function queryAvailableScraperPackages(...args: unknown[]): unknown;
      function queryFindGalleries(...args: unknown[]): unknown;
      function queryFindGalleriesByIDForSelect(...args: unknown[]): unknown;
      function queryFindGalleriesForSelect(...args: unknown[]): unknown;
      function queryFindImages(...args: unknown[]): unknown;
      function queryFindGroups(...args: unknown[]): unknown;
      function queryFindGroupsByIDForSelect(...args: unknown[]): unknown;
      function queryFindGroupsForSelect(...args: unknown[]): unknown;
      function queryFindPerformer(...args: unknown[]): unknown;
      function queryFindPerformers(...args: unknown[]): unknown;
      function queryFindPerformersByIDForSelect(...args: unknown[]): unknown;
      function queryFindPerformersForSelect(...args: unknown[]): unknown;
      function queryFindSceneMarkers(...args: unknown[]): unknown;
      function queryFindScenes(...args: unknown[]): unknown;
      function queryFindScenesByID(...args: unknown[]): unknown;
      function queryFindStudio(...args: unknown[]): unknown;
      function queryFindStudios(...args: unknown[]): unknown;
      function queryFindStudiosByIDForSelect(...args: unknown[]): unknown;
      function queryFindStudiosForSelect(...args: unknown[]): unknown;
      function queryFindTags(...args: unknown[]): unknown;
      function queryFindTagsByIDForSelect(...args: unknown[]): unknown;
      function queryFindTagsForSelect(...args: unknown[]): unknown;
      function queryLogs(...args: unknown[]): unknown;
      function queryParseSceneFilenames(...args: unknown[]): unknown;
      function querySceneByPathRegex(...args: unknown[]): unknown;
      function queryScrapeGallery(...args: unknown[]): unknown;
      function queryScrapeGalleryURL(...args: unknown[]): unknown;
      function queryScrapeGroupURL(...args: unknown[]): unknown;
      function queryScrapePerformer(...args: unknown[]): unknown;
      function queryScrapePerformerURL(...args: unknown[]): unknown;
      function queryScrapeScene(...args: unknown[]): unknown;
      function queryScrapeSceneQuery(...args: unknown[]): unknown;
      function queryScrapeSceneQueryFragment(...args: unknown[]): unknown;
      function queryScrapeSceneURL(...args: unknown[]): unknown;
      function stashBoxPerformerQuery(...args: unknown[]): unknown;
      function stashBoxSceneBatchQuery(...args: unknown[]): unknown;
      function stashBoxStudioQuery(...args: unknown[]): unknown;
      function useAddTempDLNAIP(...args: unknown[]): unknown;
      function useBulkGalleryUpdate(...args: unknown[]): unknown;
      function useBulkImageUpdate(...args: unknown[]): unknown;
      function useBulkGroupUpdate(...args: unknown[]): unknown;
      function useBulkPerformerUpdate(...args: unknown[]): unknown;
      function useBulkSceneUpdate(...args: unknown[]): unknown;
      function useConfiguration(...args: unknown[]): unknown;
      function useConfigureDLNA(...args: unknown[]): unknown;
      function useConfigureDefaults(...args: unknown[]): unknown;
      function useConfigureGeneral(...args: unknown[]): unknown;
      function useConfigureInterface(...args: unknown[]): unknown;
      function useConfigurePlugin(...args: unknown[]): unknown;
      function useConfigureScraping(...args: unknown[]): unknown;
      function useConfigureUI(...args: unknown[]): unknown;
      function useDLNAStatus(...args: unknown[]): unknown;
      function useDirectory(...args: unknown[]): unknown;
      function useDisableDLNA(...args: unknown[]): unknown;
      function useEnableDLNA(...args: unknown[]): unknown;
      function useFindDefaultFilter(...args: unknown[]): unknown;
      function useFindGalleries(...args: unknown[]): unknown;
      function useFindGallery(...args: unknown[]): unknown;
      function useFindImage(...args: unknown[]): unknown;
      function useFindImages(...args: unknown[]): unknown;
      function useFindGroup(...args: unknown[]): unknown;
      function useFindGroups(...args: unknown[]): unknown;
      function useFindPerformer(...args: unknown[]): unknown;
      function useFindPerformers(...args: unknown[]): unknown;
      function useFindSavedFilter(...args: unknown[]): unknown;
      function useFindSavedFilters(...args: unknown[]): unknown;
      function useFindScene(...args: unknown[]): unknown;
      function useFindSceneMarkers(...args: unknown[]): unknown;
      function useFindScenes(...args: unknown[]): unknown;
      function useFindStudio(...args: unknown[]): unknown;
      function useFindStudios(...args: unknown[]): unknown;
      function useFindTag(...args: unknown[]): unknown;
      function useFindTags(...args: unknown[]): unknown;
      function useGalleryChapterCreate(...args: unknown[]): unknown;
      function useGalleryChapterDestroy(...args: unknown[]): unknown;
      function useGalleryChapterUpdate(...args: unknown[]): unknown;
      function useGalleryCreate(...args: unknown[]): unknown;
      function useGalleryDestroy(...args: unknown[]): unknown;
      function useGalleryUpdate(...args: unknown[]): unknown;
      function useGenerateAPIKey(...args: unknown[]): unknown;
      function useImageDecrementO(...args: unknown[]): unknown;
      function useImageIncrementO(...args: unknown[]): unknown;
      function useImageResetO(...args: unknown[]): unknown;
      function useImageUpdate(...args: unknown[]): unknown;
      function useImagesDestroy(...args: unknown[]): unknown;
      function useInstalledPluginPackages(...args: unknown[]): unknown;
      function useInstalledScraperPackages(...args: unknown[]): unknown;
      function useJobQueue(...args: unknown[]): unknown;
      function useJobsSubscribe(...args: unknown[]): unknown;
      function useLatestVersion(...args: unknown[]): unknown;
      function useListGalleryScrapers(...args: unknown[]): unknown;
      function useListGroupScrapers(...args: unknown[]): unknown;
      function useListPerformerScrapers(...args: unknown[]): unknown;
      function useListSceneScrapers(...args: unknown[]): unknown;
      function useLoggingSubscribe(...args: unknown[]): unknown;
      function useLogs(...args: unknown[]): unknown;
      function useMarkerStrings(...args: unknown[]): unknown;
      function useGroupCreate(...args: unknown[]): unknown;
      function useGroupDestroy(...args: unknown[]): unknown;
      function useGroupUpdate(...args: unknown[]): unknown;
      function useGroupsDestroy(...args: unknown[]): unknown;
      function usePerformerCreate(...args: unknown[]): unknown;
      function usePerformerDestroy(...args: unknown[]): unknown;
      function usePerformerUpdate(...args: unknown[]): unknown;
      function usePerformersDestroy(...args: unknown[]): unknown;
      function usePluginTasks(...args: unknown[]): unknown;
      function usePlugins(...args: unknown[]): unknown;
      function useRemoveTempDLNAIP(...args: unknown[]): unknown;
      function useSaveFilter(...args: unknown[]): unknown;
      function useSavedFilterDestroy(...args: unknown[]): unknown;
      function useSceneDecrementO(...args: unknown[]): unknown;
      function useSceneDestroy(...args: unknown[]): unknown;
      function useSceneGenerateScreenshot(...args: unknown[]): unknown;
      function useSceneIncrementO(...args: unknown[]): unknown;
      function useSceneIncrementPlayCount(...args: unknown[]): unknown;
      function useSceneMarkerCreate(...args: unknown[]): unknown;
      function useSceneMarkerDestroy(...args: unknown[]): unknown;
      function useSceneMarkerUpdate(...args: unknown[]): unknown;
      function useSceneResetO(...args: unknown[]): unknown;
      function useSceneSaveActivity(...args: unknown[]): unknown;
      function useSceneStreams(...args: unknown[]): unknown;
      function useSceneUpdate(...args: unknown[]): unknown;
      function useScenesDestroy(...args: unknown[]): unknown;
      function useScenesUpdate(...args: unknown[]): unknown;
      function useScrapePerformerList(...args: unknown[]): unknown;
      function useSetDefaultFilter(...args: unknown[]): unknown;
      function useStats(...args: unknown[]): unknown;
      function useStudioCreate(...args: unknown[]): unknown;
      function useStudioDestroy(...args: unknown[]): unknown;
      function useStudioUpdate(...args: unknown[]): unknown;
      function useStudiosDestroy(...args: unknown[]): unknown;
      function useSystemStatus(...args: unknown[]): unknown;
      function useTagCreate(...args: unknown[]): unknown;
      function useTagDestroy(...args: unknown[]): unknown;
      function useTagUpdate(...args: unknown[]): unknown;
      function useTagsDestroy(...args: unknown[]): unknown;
      function useTagsMerge(...args: unknown[]): unknown;
      function useVersion(...args: unknown[]): unknown;

      const performerMutationImpactedQueries: { [key: string]: unknown }[];
      const pluginMutationImpactedQueries: { [key: string]: unknown }[];
      const scraperMutationImpactedQueries: { [key: string]: unknown }[];
      const studioMutationImpactedQueries: { [key: string]: unknown }[];
    }
    function loadComponents(components: (() => Promise<unknown>)[]): void;
  }
  namespace hooks {
    function useLoadComponents(toLoad: (() => Promise<unknown>)[]): boolean;
    function useSpriteInfo(vttPath: string | undefined):
      | {
          url: string;
          start: number;
          end: number;
          x: number;
          y: number;
          w: number;
          h: number;
        }
      | undefined;

    function useToast(): {
      toast: unknown;
      success(message: JSX.Element | string): void;
      error(error: unknown): void;
    };

    function useSettings(): {
      loading: boolean;
      error: unknown | undefined;
      general: unknown;
      interface: unknown;
      defaults: unknown;
      scraping: unknown;
      dlna: unknown;
      ui: unknown;
      plugins: unknown;

      advancedMode: boolean;

      // apikey isn't directly settable, so expose it here
      apiKey: string;

      saveGeneral: (input: unknown) => void;
      saveInterface: (input: unknown) => void;
      saveDefaults: (input: unknown) => void;
      saveScraping: (input: unknown) => void;
      saveDLNA: (input: unknown) => void;
      saveUI: (input: unknown) => void;
      savePluginSettings: (pluginID: string, input: object) => void;
      setAdvancedMode: (value: boolean) => void;

      refetch: () => void;
    };
    export enum ConnectionState {
      Missing,
      Disconnected,
      Error,
      Connecting,
      Syncing,
      Uploading,
      Ready,
    }

    type Handy = typeof import("thehandy").default;
    export type InteractiveAPI = {
      readonly _connected: boolean;
      readonly _playing: boolean;
      readonly _scriptOffset: number;
      readonly _handy: Handy;
      readonly _useStashHostedFunscript: boolean;
      connect(): Promise<void>;
      set handyKey(key: string);
      get handyKey(): string;
      set useStashHostedFunscript(useStashHostedFunscript: boolean);
      get useStashHostedFunscript(): boolean;
      set scriptOffset(offset: number);
      uploadScript(funscriptPath: string, apiKey?: string): Promise<void>;
      sync(): Promise<number>;
      setServerTimeOffset(offset: number): void;
      play(position: number): Promise<void>;
      pause(): Promise<void>;
      ensurePlaying(position: number): Promise<void>;
      setLooping(looping: boolean): Promise<void>;
    };

    function useInteractive(): {
      interactive: InteractiveAPI;
      state: ConnectionState;
      serverOffset: number;
      initialised: boolean;
      currentScript?: string;
      error?: string;
      initialise: () => Promise<void>;
      uploadScript: (funscriptPath: string) => Promise<void>;
      sync: () => Promise<void>;
    };
  }
  namespace patch {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
    function before(target: PatchableComponentNames, fn: Function): void;
    // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
    function instead(target: PatchableComponentNames, fn: Function): void;
    // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
    function after(target: PatchableComponentNames, fn: Function): void;
  }
  namespace register {
    function route(path: string, component: React.FC<unknown>): void;
  }
}

declare module "mousetrap-pause" {
  import { MousetrapStatic } from "mousetrap";

  function MousetrapPause(mousetrap: MousetrapStatic): MousetrapStatic;

  export default MousetrapPause;

  module "mousetrap" {
    interface MousetrapStatic {
      pause(): void;
      unpause(): void;
      pauseCombo(combo: string): void;
      unpauseCombo(combo: string): void;
    }
    interface MousetrapInstance {
      pause(): void;
      unpause(): void;
      pauseCombo(combo: string): void;
      unpauseCombo(combo: string): void;
    }
  }
}
